export const englishToUrduMap: { [key: string]: string } = {
  why: "کیوں",
  do: "کرنا",
  should: "چاہیے",
  you: "آپ",
  exercise: "ورزش",
  chest: "سینہ",
  muscles: "عضلات",
  help: "مدد",
  develop: "ترقی",
  exercises: "ورزشیں",
  detail: "تفصیل",
  effective: "موثر",
  way: "طریقہ",
  warmup: "گرم_اپ",
  improve: "بہتر",
  posture: "انداز",
  mobility: "نقل_و_حرکت",
  importance: "اہمیت",
  build: "بنانا",
  press: "دبانا",
  bench: "بینچ",
  this: "اس",
  is: "ہے",
  of: "ہے_کی",
  how: "کیسے",
  here: "یہاں",
  perform: "انجام_دینا",
  explore: "جانیں",
  helpful: "مدد_گار",
  before: "پہلے",
  work: "کام",
  come: "آؤ",
  out: "آؤٹ",
  "ice cream": "آئسکریم",
  ice: "آئس",
  oil: "آئل",
  constitution: "آئن",
  mirror: "آئینہ",
  constitutional: "آئینی",
  item: "آئٹم",
  ideology: "آئڈیالوجی",
  ideal: "آئڈیل",
  came: "آئی",
  it: "آئی_ٹی",
  idea: "آئیڈیا",
  ideas: "آئیڈیاز",
  "come (plural)": "آئیں",
  "please come": "آئیے",
  water: "آب",
  population: "آبادی",
  communities: "آبادیوں",
  honor: "آبرو",
  dignified: "آبروئی",
  "honor of": "آبروئے",
  respectable: "آبرو_مند",
  dishonor: "آبرو_ریزی",
  "preserve honor": "آبرو_کا_پاس",
  ireland: "آئیرلینڈ",
  irish: "آئرش",
  leaders: "آئمہ",
  "will come": "آئیگی",
  came2: "آئے",
  income: "آئےتن",
  climate: "آب_و_ہوا",
  vividness: "آب_و_رنگ",
  "earth and water": "آب_و_گل",
  glory: "آب_و_تاب",
  irrigation: "آب_پاشی",
  hydraulic: "آب_کاری",
  strainer: "آب_کش",
  flooded: "آب_خیز",
  waterfall: "آب_شار",
  urination: "آب_دست",
  "silver water": "آب_نقرہ",
  "ice water": "آب_یخ",
};

export const englishToUrduPhrases = {
  "chest exercises": "سینے کی ورزشیں",
  "chest workouts": "سینے کی ورزشیں",
  "develop chest muscles": "سینے کے پٹھے بنانے میں مدد دیتی ہیں",
  "here’s how to perform it": "اسے کرنے کا طریقہ یہ ہے",
  "this bench press is a great way": "بینچ پریس ایک بہترین طریقہ ہے",
  "to work on your chest muscles": "اپنے سینے کے پٹھوں پر کام کرنے کا",
  "you know the importance of chest exercises":
    "آپ سینے کی ورزشوں کی اہمیت جانتے ہیں",
  "now let’s explore these exercises in detail":
    "اب آئیے ان ورزشوں کو تفصیل سے دیکھتے ہیں",
  "discuss how you should perform them effectively":
    "اور بات کرتے ہیں کہ انہیں مؤثر طریقے سے کیسے کرنا ہے",
  "helpful chest warm-up": "مددگار سینے کی وارم اپ ورزش",
  "before work": "ورزش شروع کرنے سے پہلے",
  "here’s how to do it": "اسے کرنے کا طریقہ درج ذیل ہے",
  "build the chest muscles": "سینے کے پٹھے بناتی ہے",
  "improves posture and mobility": "چال، انداز اور حرکت میں بہتری لاتی ہے",
  "mental fatigue": "ذہنی تھکن",
  "mental exhaustion": "ذہنی تھکاوٹ",
  "chronic health issues": "دائمی صحت کے مسائل",
  "everyday stress": "روزمرہ کا ذہنی دباؤ",
  "feeling worn out": "تھکن محسوس کرنا",
  "from work": "کام سے",
  burnout: "بڑھتی ہوئی تھکن (برن آؤٹ)",
  "don’t overlook it": "اسے نظرانداز نہ کریں",
  "you are going through": "آپ گزر رہے ہیں",
  "if you have some of these symptoms":
    "اگر آپ کو ان میں سے کچھ علامات محسوس ہوں",
  "you know you are going through mental fatigue":
    "آپ جان سکتے ہیں کہ آپ ذہنی تھکن کا شکار ہیں",
  "get mental fatigue": "ذہنی تھکن محسوس ہو سکتی ہے",
  "for many reasons": "کئی وجوہات کی بنا پر",
  sometimes: "کبھی کبھار",
  "due to chronic health issues": "دائمی صحت کے مسائل کی وجہ سے",
  "how is mental exhaustion different from": "ذہنی تھکن کس طرح مختلف ہے",
  "we must pay extra attention": "ہمیں خاص توجہ دینی چاہیے",
  "to our brain and cognitive health": "اپنے دماغ اور ذہنی صحت پر",
  "in this fast-paced time": "آج کے تیز رفتار دور میں",
};
